name: Test dualFuelEngine-dev

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

#   push:
#     branches:
#       - 'develop'

jobs:
  tutorials-tubes:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Install OpenFOAM-dev
      run: |
        sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
        sudo apt update
        sudo apt install -y openfoam-dev
        . /opt/openfoam-dev/etc/bashrc && tutorials/RiemannTube/./Allrun

    - name: RiemannTube
      run: |
        cat README.md
        . /opt/openfoam-dev/etc/bashrc
        foamVersion
        tutorials/RiemannTube/./Allrun

    - name: shockTube
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/shockTube/shockTube_multiCompressionFoam/./Allrun

    - name: tubePurging
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/tubePurging/tubePurging_multiCompressionFoam/./Allrun

    - name: pipeCompression
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/pipeCompression/pipeCompression_multiCompressionFoam/./Allrun

    - name: quadPiston
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/quadPiston/./Allrun
    
