name: simpleTutorials

on:
  push:
    tags-ignore:
      - v*

jobs:
  simpleTutorials:
    runs-on: ubuntu-18.04
    # container: openfoam/openfoam-dev-graphical-apps

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install OpenFOAM-dev
      run: |
        sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
        sudo apt update
        sudo apt install -y openfoam-dev

    # Run the multiCompressionFoam cases
    - name: RiemannTube
      run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
      working-directory: tutorials/multiCompressionFoam/RiemannTube
    - name: shockTube
      run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
      working-directory: tutorials/multiCompressionFoam/shockTube/shockTube_multiCompressionFoam
    - name: tubePurging
      run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
      working-directory: tutorials/multiCompressionFoam/tubePurging/tubePurging_multiCompressionFoam
    - name: pipeCompression
      run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
      working-directory: tutorials/multiCompressionFoam/pipeCompression/pipeCompression_multiCompressionFoam
    - name: quadPiston
      run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
      working-directory: tutorials/multiCompressionFoam/quadPiston

    # Save log.multiCompressionFoam as artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: multiCompressionFoam logs
        path: tutorials/**/log.multiCompressionFoam
