name: Test dualFuelEngine-dev

on: push

jobs:
  tutorials-tubes:
    runs-on: ubuntu-18.04
    defaults:
      uses: actions/upload-artifact@v1
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v1
      
    - name: Install OpenFOAM-dev
      run: |
        sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
        sudo apt update
        sudo apt install -y openfoam-dev

    - name: RiemannTube
      run: . /opt/openfoam-dev/etc/bashrc && blockMesh && setFields && multiCompressionFoam
      working-directory: tutorials/multiCompressionFoam/RiemannTube
      with:
        name: RiemannTube log
        path: log.multiCompressionFoam

    - name: RiemannTube
      run: . /opt/openfoam-dev/etc/bashrc && ./Allrun
      working-directory: tutorials/multiCompressionFoam/RiemannTube
      with:
        name: RiemannTube log
        path: log.multiCompressionFoam

    - name: RiemannTube
      run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
      working-directory: tutorials/multiCompressionFoam/RiemannTube
      with:
        name: RiemannTube log
        path: log.multiCompressionFoam

    # - name: shockTube
    #   run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
    #   working-directory: tutorials/multiCompressionFoam/shockTube/shockTube_multiCompressionFoam
    #
    # - name: tubePurging
    #   run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
    #   working-directory: tutorials/multiCompressionFoam/tubePurging/tubePurging_multiCompressionFoam
    #
    # - name: pipeCompression
    #   run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
    #   working-directory: tutorials/multiCompressionFoam/pipeCompression/pipeCompression_multiCompressionFoam
    #
    # - name: quadPiston
    #   run: . /opt/openfoam-dev/etc/bashrc && foamRunTutorials
    #   working-directory: tutorials/multiCompressionFoam/quadPiston
