name: Test dualFuelEngine-dev

on:
  push:
    branches: [ develop ]

jobs:
  fastAllrun:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Install OpenFOAM-dev
      run: |
        sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
        sudo apt update
        sudo apt install -y openfoam-dev
        source /opt/openfoam-dev/etc/bashrc && echo $WM_PROJECT-$WM_PROJECT_VERSION is installed!

    - name: wmake solver
      run: solvers/./Allwmake && echo wmake is finished successfull!

    - name: RiemannTube
      run: tutorials/RiemannTube/./Allrun
    - name: shockTube
      run: tutorials/shockTube/shockTube_multiCompressionFoam/./Allrun
    - name: tubePurging
      run: tutorials/tubePurging/tubePurging_multiCompressionFoam/./Allrun
    - name: pipeCompression
      run: tutorials/pipeCompression/pipeCompression_multiCompressionFoam/./Allrun
    - name: quadPiston
      run: tutorials/quadPiston/./Allrun
    - name: cylCyclic2D
      run: tutorials/cylCyclic2D/cylCyclic2D_multiCompressionFoam/./Allrun
    - name: cylPiston
      run: tutorials/cylPiston/cylPiston_multiCompressionFoam/./Allrun
    
