name: Test dualFuelEngine-dev

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ test ]


jobs:
  fastAllrun:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Install OpenFOAM-dev
      run: |
        sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
        sudo apt update
        sudo apt install -y openfoam-dev

    - name: wmake solver
      run: . /opt/openfoam-dev/etc/bashrc && solvers/./Allwmake && echo wmake is finished successfull!

    - name: RiemannTube
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/RiemannTube/./Allrun
    - name: shockTube
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/shockTube/shockTube_multiCompressionFoam/./Allrun
    - name: tubePurging
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/tubePurging/tubePurging_multiCompressionFoam/./Allrun
    - name: pipeCompression
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/pipeCompression/pipeCompression_multiCompressionFoam/./Allrun
    - name: quadPiston
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/quadPiston/./Allrun
    - name: cylCyclic2D
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/cylCyclic2D/cylCyclic2D_multiCompressionFoam/./Allrun
    - name: cylPiston
      run: . /opt/openfoam-dev/etc/bashrc && tutorials/cylPiston/cylPiston_multiCompressionFoam/./Allrun
    
